backbone: "mobilenetv3_large_100"

trainer:
  gpus: 1
  #limit_train_batches: 500
  val_check_interval: 0.25
  enable_checkpointing: True
  logger: True
  max_epochs: 15
  resume_from_checkpoint: "checkpoints/configs/mn100RGBNir_BioCAL-val_loss=6.34067-epoch=2.ckpt"

early_stopping: False

optimizer_params: 
  lr: 0.001

datamodule:
  batch_size: 550
  num_workers: 4
  train_trans:
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    Rotate:
      limit: 30
      p: 0.8
    RandomBrightnessContrast:
      brightness_limit: 0.1
      contrast_limit: 0.1
      p: 0.8

