backbone: "gluon_resnext50_32x4d"

trainer:
  gpus: 1
  #limit_train_batches: 500
  val_check_interval: 0.1
  enable_checkpointing: True
  logger: True
  max_epochs: 50
  resume_from_checkpoint: "checkpoints/configs/trlNirGBAltBio-val_loss=6.76263-epoch=0.ckpt"

early_stopping: False

datamodule:
  batch_size: 220
  num_workers: 6
  train_trans:
    HorizontalFlip:
      p: 0.5
    VerticalFlip:
      p: 0.5
    Rotate:
      limit: 25
      p: 0.8

